/**
 * Do not edit directly
 * Generated on Thu, 30 Dec 2021 00:33:21 GMT
 */

module.exports = {
  typography: {
    tiny: {
      fontSize: {
        type: 'dimension',
        value: 10,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 10,
        },
        name: 'TypographyTinyFontSize',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'fontSize',
        },
        path: ['typography', 'tiny', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyTinyTextDecoration',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'textDecoration',
        },
        path: ['typography', 'tiny', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyTinyFontFamily',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'fontFamily',
        },
        path: ['typography', 'tiny', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 600,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 600,
        },
        name: 'TypographyTinyFontWeight',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'fontWeight',
        },
        path: ['typography', 'tiny', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyTinyFontStyle',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'fontStyle',
        },
        path: ['typography', 'tiny', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyTinyFontStretch',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'fontStretch',
        },
        path: ['typography', 'tiny', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTinyLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'letterSpacing',
        },
        path: ['typography', 'tiny', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 16,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 16,
        },
        name: 'TypographyTinyLineHeight',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'lineHeight',
        },
        path: ['typography', 'tiny', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTinyParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'paragraphIndent',
        },
        path: ['typography', 'tiny', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTinyParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'tiny', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyTinyTextCase',
        attributes: {
          category: 'typography',
          type: 'tiny',
          item: 'textCase',
        },
        path: ['typography', 'tiny', 'textCase'],
      },
    },
    caption: {
      fontSize: {
        type: 'dimension',
        value: 12,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 12,
        },
        name: 'TypographyCaptionFontSize',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'fontSize',
        },
        path: ['typography', 'caption', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyCaptionTextDecoration',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'textDecoration',
        },
        path: ['typography', 'caption', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyCaptionFontFamily',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'fontFamily',
        },
        path: ['typography', 'caption', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 500,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 500,
        },
        name: 'TypographyCaptionFontWeight',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'fontWeight',
        },
        path: ['typography', 'caption', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyCaptionFontStyle',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'fontStyle',
        },
        path: ['typography', 'caption', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyCaptionFontStretch',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'fontStretch',
        },
        path: ['typography', 'caption', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyCaptionLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'letterSpacing',
        },
        path: ['typography', 'caption', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 20,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 20,
        },
        name: 'TypographyCaptionLineHeight',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'lineHeight',
        },
        path: ['typography', 'caption', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyCaptionParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'paragraphIndent',
        },
        path: ['typography', 'caption', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyCaptionParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'caption', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyCaptionTextCase',
        attributes: {
          category: 'typography',
          type: 'caption',
          item: 'textCase',
        },
        path: ['typography', 'caption', 'textCase'],
      },
    },
    'small body alt': {
      fontSize: {
        type: 'dimension',
        value: 14,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 14,
        },
        name: 'TypographySmallBodyAltFontSize',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'fontSize',
        },
        path: ['typography', 'small body alt', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographySmallBodyAltTextDecoration',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'textDecoration',
        },
        path: ['typography', 'small body alt', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographySmallBodyAltFontFamily',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'fontFamily',
        },
        path: ['typography', 'small body alt', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 700,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 700,
        },
        name: 'TypographySmallBodyAltFontWeight',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'fontWeight',
        },
        path: ['typography', 'small body alt', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographySmallBodyAltFontStyle',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'fontStyle',
        },
        path: ['typography', 'small body alt', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographySmallBodyAltFontStretch',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'fontStretch',
        },
        path: ['typography', 'small body alt', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySmallBodyAltLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'letterSpacing',
        },
        path: ['typography', 'small body alt', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 24,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 24,
        },
        name: 'TypographySmallBodyAltLineHeight',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'lineHeight',
        },
        path: ['typography', 'small body alt', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySmallBodyAltParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'paragraphIndent',
        },
        path: ['typography', 'small body alt', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySmallBodyAltParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'small body alt', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographySmallBodyAltTextCase',
        attributes: {
          category: 'typography',
          type: 'small body alt',
          item: 'textCase',
        },
        path: ['typography', 'small body alt', 'textCase'],
      },
    },
    'small body': {
      fontSize: {
        type: 'dimension',
        value: 14,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 14,
        },
        name: 'TypographySmallBodyFontSize',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'fontSize',
        },
        path: ['typography', 'small body', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographySmallBodyTextDecoration',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'textDecoration',
        },
        path: ['typography', 'small body', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographySmallBodyFontFamily',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'fontFamily',
        },
        path: ['typography', 'small body', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 500,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 500,
        },
        name: 'TypographySmallBodyFontWeight',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'fontWeight',
        },
        path: ['typography', 'small body', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographySmallBodyFontStyle',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'fontStyle',
        },
        path: ['typography', 'small body', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographySmallBodyFontStretch',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'fontStretch',
        },
        path: ['typography', 'small body', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySmallBodyLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'letterSpacing',
        },
        path: ['typography', 'small body', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 24,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 24,
        },
        name: 'TypographySmallBodyLineHeight',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'lineHeight',
        },
        path: ['typography', 'small body', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySmallBodyParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'paragraphIndent',
        },
        path: ['typography', 'small body', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySmallBodyParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'small body', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographySmallBodyTextCase',
        attributes: {
          category: 'typography',
          type: 'small body',
          item: 'textCase',
        },
        path: ['typography', 'small body', 'textCase'],
      },
    },
    'body alt': {
      fontSize: {
        type: 'dimension',
        value: 16,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 16,
        },
        name: 'TypographyBodyAltFontSize',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'fontSize',
        },
        path: ['typography', 'body alt', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyBodyAltTextDecoration',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'textDecoration',
        },
        path: ['typography', 'body alt', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyBodyAltFontFamily',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'fontFamily',
        },
        path: ['typography', 'body alt', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 700,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 700,
        },
        name: 'TypographyBodyAltFontWeight',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'fontWeight',
        },
        path: ['typography', 'body alt', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyBodyAltFontStyle',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'fontStyle',
        },
        path: ['typography', 'body alt', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyBodyAltFontStretch',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'fontStretch',
        },
        path: ['typography', 'body alt', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyBodyAltLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'letterSpacing',
        },
        path: ['typography', 'body alt', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 28,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 28,
        },
        name: 'TypographyBodyAltLineHeight',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'lineHeight',
        },
        path: ['typography', 'body alt', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyBodyAltParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'paragraphIndent',
        },
        path: ['typography', 'body alt', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyBodyAltParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'body alt', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyBodyAltTextCase',
        attributes: {
          category: 'typography',
          type: 'body alt',
          item: 'textCase',
        },
        path: ['typography', 'body alt', 'textCase'],
      },
    },
    body: {
      fontSize: {
        type: 'dimension',
        value: 16,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 16,
        },
        name: 'TypographyBodyFontSize',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'fontSize',
        },
        path: ['typography', 'body', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyBodyTextDecoration',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'textDecoration',
        },
        path: ['typography', 'body', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyBodyFontFamily',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'fontFamily',
        },
        path: ['typography', 'body', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 500,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 500,
        },
        name: 'TypographyBodyFontWeight',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'fontWeight',
        },
        path: ['typography', 'body', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyBodyFontStyle',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'fontStyle',
        },
        path: ['typography', 'body', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyBodyFontStretch',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'fontStretch',
        },
        path: ['typography', 'body', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyBodyLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'letterSpacing',
        },
        path: ['typography', 'body', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 28,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 28,
        },
        name: 'TypographyBodyLineHeight',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'lineHeight',
        },
        path: ['typography', 'body', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyBodyParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'paragraphIndent',
        },
        path: ['typography', 'body', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyBodyParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'body', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyBodyTextCase',
        attributes: {
          category: 'typography',
          type: 'body',
          item: 'textCase',
        },
        path: ['typography', 'body', 'textCase'],
      },
    },
    subtitle: {
      fontSize: {
        type: 'dimension',
        value: 20,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 20,
        },
        name: 'TypographySubtitleFontSize',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'fontSize',
        },
        path: ['typography', 'subtitle', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographySubtitleTextDecoration',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'textDecoration',
        },
        path: ['typography', 'subtitle', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographySubtitleFontFamily',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'fontFamily',
        },
        path: ['typography', 'subtitle', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 800,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 800,
        },
        name: 'TypographySubtitleFontWeight',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'fontWeight',
        },
        path: ['typography', 'subtitle', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographySubtitleFontStyle',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'fontStyle',
        },
        path: ['typography', 'subtitle', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographySubtitleFontStretch',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'fontStretch',
        },
        path: ['typography', 'subtitle', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 1,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 1,
        },
        name: 'TypographySubtitleLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'letterSpacing',
        },
        path: ['typography', 'subtitle', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 32,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 32,
        },
        name: 'TypographySubtitleLineHeight',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'lineHeight',
        },
        path: ['typography', 'subtitle', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySubtitleParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'paragraphIndent',
        },
        path: ['typography', 'subtitle', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographySubtitleParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'subtitle', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographySubtitleTextCase',
        attributes: {
          category: 'typography',
          type: 'subtitle',
          item: 'textCase',
        },
        path: ['typography', 'subtitle', 'textCase'],
      },
    },
    'title 2': {
      fontSize: {
        type: 'dimension',
        value: 28,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 28,
        },
        name: 'TypographyTitle2FontSize',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'fontSize',
        },
        path: ['typography', 'title 2', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyTitle2TextDecoration',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'textDecoration',
        },
        path: ['typography', 'title 2', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyTitle2FontFamily',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'fontFamily',
        },
        path: ['typography', 'title 2', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 900,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 900,
        },
        name: 'TypographyTitle2FontWeight',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'fontWeight',
        },
        path: ['typography', 'title 2', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyTitle2FontStyle',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'fontStyle',
        },
        path: ['typography', 'title 2', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyTitle2FontStretch',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'fontStretch',
        },
        path: ['typography', 'title 2', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 1.54,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 1.54,
        },
        name: 'TypographyTitle2LetterSpacing',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'letterSpacing',
        },
        path: ['typography', 'title 2', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 40,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 40,
        },
        name: 'TypographyTitle2LineHeight',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'lineHeight',
        },
        path: ['typography', 'title 2', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTitle2ParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'paragraphIndent',
        },
        path: ['typography', 'title 2', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTitle2ParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'title 2', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'uppercase',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'uppercase',
        },
        name: 'TypographyTitle2TextCase',
        attributes: {
          category: 'typography',
          type: 'title 2',
          item: 'textCase',
        },
        path: ['typography', 'title 2', 'textCase'],
      },
    },
    title: {
      fontSize: {
        type: 'dimension',
        value: 32,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 32,
        },
        name: 'TypographyTitleFontSize',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'fontSize',
        },
        path: ['typography', 'title', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyTitleTextDecoration',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'textDecoration',
        },
        path: ['typography', 'title', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyTitleFontFamily',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'fontFamily',
        },
        path: ['typography', 'title', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 900,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 900,
        },
        name: 'TypographyTitleFontWeight',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'fontWeight',
        },
        path: ['typography', 'title', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyTitleFontStyle',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'fontStyle',
        },
        path: ['typography', 'title', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyTitleFontStretch',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'fontStretch',
        },
        path: ['typography', 'title', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 1.6,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 1.6,
        },
        name: 'TypographyTitleLetterSpacing',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'letterSpacing',
        },
        path: ['typography', 'title', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 44,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 44,
        },
        name: 'TypographyTitleLineHeight',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'lineHeight',
        },
        path: ['typography', 'title', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTitleParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'paragraphIndent',
        },
        path: ['typography', 'title', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyTitleParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'title', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyTitleTextCase',
        attributes: {
          category: 'typography',
          type: 'title',
          item: 'textCase',
        },
        path: ['typography', 'title', 'textCase'],
      },
    },
    'display 3': {
      fontSize: {
        type: 'dimension',
        value: 40,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 40,
        },
        name: 'TypographyDisplay3FontSize',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'fontSize',
        },
        path: ['typography', 'display 3', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyDisplay3TextDecoration',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'textDecoration',
        },
        path: ['typography', 'display 3', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyDisplay3FontFamily',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'fontFamily',
        },
        path: ['typography', 'display 3', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 900,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 900,
        },
        name: 'TypographyDisplay3FontWeight',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'fontWeight',
        },
        path: ['typography', 'display 3', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyDisplay3FontStyle',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'fontStyle',
        },
        path: ['typography', 'display 3', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyDisplay3FontStretch',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'fontStretch',
        },
        path: ['typography', 'display 3', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 2.2,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 2.2,
        },
        name: 'TypographyDisplay3LetterSpacing',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'letterSpacing',
        },
        path: ['typography', 'display 3', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 56,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 56,
        },
        name: 'TypographyDisplay3LineHeight',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'lineHeight',
        },
        path: ['typography', 'display 3', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyDisplay3ParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'paragraphIndent',
        },
        path: ['typography', 'display 3', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyDisplay3ParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'display 3', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'uppercase',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'uppercase',
        },
        name: 'TypographyDisplay3TextCase',
        attributes: {
          category: 'typography',
          type: 'display 3',
          item: 'textCase',
        },
        path: ['typography', 'display 3', 'textCase'],
      },
    },
    'display 2': {
      fontSize: {
        type: 'dimension',
        value: 48,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 48,
        },
        name: 'TypographyDisplay2FontSize',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'fontSize',
        },
        path: ['typography', 'display 2', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyDisplay2TextDecoration',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'textDecoration',
        },
        path: ['typography', 'display 2', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyDisplay2FontFamily',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'fontFamily',
        },
        path: ['typography', 'display 2', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 900,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 900,
        },
        name: 'TypographyDisplay2FontWeight',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'fontWeight',
        },
        path: ['typography', 'display 2', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyDisplay2FontStyle',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'fontStyle',
        },
        path: ['typography', 'display 2', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyDisplay2FontStretch',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'fontStretch',
        },
        path: ['typography', 'display 2', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 2.64,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 2.64,
        },
        name: 'TypographyDisplay2LetterSpacing',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'letterSpacing',
        },
        path: ['typography', 'display 2', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 56,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 56,
        },
        name: 'TypographyDisplay2LineHeight',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'lineHeight',
        },
        path: ['typography', 'display 2', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyDisplay2ParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'paragraphIndent',
        },
        path: ['typography', 'display 2', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyDisplay2ParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'display 2', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'uppercase',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'uppercase',
        },
        name: 'TypographyDisplay2TextCase',
        attributes: {
          category: 'typography',
          type: 'display 2',
          item: 'textCase',
        },
        path: ['typography', 'display 2', 'textCase'],
      },
    },
    'display 1': {
      fontSize: {
        type: 'dimension',
        value: 56,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 56,
        },
        name: 'TypographyDisplay1FontSize',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'fontSize',
        },
        path: ['typography', 'display 1', 'fontSize'],
      },
      textDecoration: {
        type: 'string',
        value: 'none',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'none',
        },
        name: 'TypographyDisplay1TextDecoration',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'textDecoration',
        },
        path: ['typography', 'display 1', 'textDecoration'],
      },
      fontFamily: {
        type: 'string',
        value: 'Poppins',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'Poppins',
        },
        name: 'TypographyDisplay1FontFamily',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'fontFamily',
        },
        path: ['typography', 'display 1', 'fontFamily'],
      },
      fontWeight: {
        type: 'number',
        value: 900,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'number',
          value: 900,
        },
        name: 'TypographyDisplay1FontWeight',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'fontWeight',
        },
        path: ['typography', 'display 1', 'fontWeight'],
      },
      fontStyle: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyDisplay1FontStyle',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'fontStyle',
        },
        path: ['typography', 'display 1', 'fontStyle'],
      },
      fontStretch: {
        type: 'string',
        value: 'normal',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'normal',
        },
        name: 'TypographyDisplay1FontStretch',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'fontStretch',
        },
        path: ['typography', 'display 1', 'fontStretch'],
      },
      letterSpacing: {
        type: 'dimension',
        value: 3.08,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 3.08,
        },
        name: 'TypographyDisplay1LetterSpacing',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'letterSpacing',
        },
        path: ['typography', 'display 1', 'letterSpacing'],
      },
      lineHeight: {
        type: 'dimension',
        value: 56,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 56,
        },
        name: 'TypographyDisplay1LineHeight',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'lineHeight',
        },
        path: ['typography', 'display 1', 'lineHeight'],
      },
      paragraphIndent: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyDisplay1ParagraphIndent',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'paragraphIndent',
        },
        path: ['typography', 'display 1', 'paragraphIndent'],
      },
      paragraphSpacing: {
        type: 'dimension',
        value: 0,
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'dimension',
          value: 0,
        },
        name: 'TypographyDisplay1ParagraphSpacing',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'paragraphSpacing',
        },
        path: ['typography', 'display 1', 'paragraphSpacing'],
      },
      textCase: {
        type: 'string',
        value: 'uppercase',
        filePath: 'src/Theme/design-tokens.tokens.json',
        isSource: true,
        original: {
          type: 'string',
          value: 'uppercase',
        },
        name: 'TypographyDisplay1TextCase',
        attributes: {
          category: 'typography',
          type: 'display 1',
          item: 'textCase',
        },
        path: ['typography', 'display 1', 'textCase'],
      },
    },
  },
};
