import * as Colors from './colors';
import typeTokens from './typography-tokens';

const styles = {
  display1: {
    fontSize: typeTokens.typography['display 1'].fontSize.value,
    lineHeight: typeTokens.typography['display 1'].lineHeight.value,
    fontWeight: typeTokens.typography['display 1'].fontWeight.value,
    letterSpacing: typeTokens.typography['display 1'].letterSpacing.value,
    textTransform: typeTokens.typography['display 1'].textCase.value,
    fontFamily: typeTokens.typography['display 1'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  display2: {
    fontSize: typeTokens.typography['display 2'].fontSize.value,
    lineHeight: typeTokens.typography['display 2'].lineHeight.value,
    fontWeight: typeTokens.typography['display 2'].fontWeight.value,
    letterSpacing: typeTokens.typography['display 2'].letterSpacing.value,
    textTransform: typeTokens.typography['display 2'].textCase.value,
    fontFamily: typeTokens.typography['display 2'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  display3: {
    fontSize: typeTokens.typography['display 3'].fontSize.value,
    lineHeight: typeTokens.typography['display 3'].lineHeight.value,
    fontWeight: typeTokens.typography['display 3'].fontWeight.value,
    letterSpacing: typeTokens.typography['display 3'].letterSpacing.value,
    textTransform: typeTokens.typography['display 3'].textCase.value,
    fontFamily: typeTokens.typography['display 3'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  title: {
    fontSize: typeTokens.typography.title.fontSize.value,
    lineHeight: typeTokens.typography.title.lineHeight.value,
    fontWeight: typeTokens.typography.title.fontWeight.value,
    letterSpacing: typeTokens.typography.title.letterSpacing.value,
    textTransform: typeTokens.typography.title.textCase.value,
    fontFamily: typeTokens.typography.title.fontFamily.value,
    color: Colors.ColorTextLight,
  },
  title2: {
    fontSize: typeTokens.typography['title 2'].fontSize.value,
    lineHeight: typeTokens.typography['title 2'].lineHeight.value,
    fontWeight: typeTokens.typography['title 2'].fontWeight.value,
    letterSpacing: typeTokens.typography['title 2'].letterSpacing.value,
    textTransform: typeTokens.typography['title 2'].textCase.value,
    fontFamily: typeTokens.typography['title 2'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  subtitle: {
    fontSize: typeTokens.typography.subtitle.fontSize.value,
    lineHeight: typeTokens.typography.subtitle.lineHeight.value,
    fontWeight: typeTokens.typography.subtitle.fontWeight.value,
    letterSpacing: typeTokens.typography.subtitle.letterSpacing.value,
    textTransform: typeTokens.typography.subtitle.textCase.value,
    fontFamily: typeTokens.typography.subtitle.fontFamily.value,
    color: Colors.ColorTextLight,
  },
  body: {
    fontSize: typeTokens.typography.body.fontSize.value,
    lineHeight: typeTokens.typography.body.lineHeight.value,
    fontWeight: typeTokens.typography.body.fontWeight.value,
    letterSpacing: typeTokens.typography.body.letterSpacing.value,
    textTransform: typeTokens.typography.body.textCase.value,
    fontFamily: typeTokens.typography.body.fontFamily.value,
    color: Colors.ColorTextLight,
  },
  bodyAlt: {
    fontSize: typeTokens.typography['body alt'].fontSize.value,
    lineHeight: typeTokens.typography['body alt'].lineHeight.value,
    fontWeight: typeTokens.typography['body alt'].fontWeight.value,
    letterSpacing: typeTokens.typography['body alt'].letterSpacing.value,
    textTransform: typeTokens.typography['body alt'].textCase.value,
    fontFamily: typeTokens.typography['body alt'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  smallBody: {
    fontSize: typeTokens.typography['small body'].fontSize.value,
    lineHeight: typeTokens.typography['small body'].lineHeight.value,
    fontWeight: typeTokens.typography['small body'].fontWeight.value,
    letterSpacing: typeTokens.typography['small body'].letterSpacing.value,
    textTransform: typeTokens.typography['small body'].textCase.value.value,
    fontFamily: typeTokens.typography['small body'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  smallBodyAlt: {
    fontSize: typeTokens.typography['small body alt'].fontSize.value,
    lineHeight: typeTokens.typography['small body alt'].lineHeight.value,
    fontWeight: typeTokens.typography['small body alt'].fontWeight.value,
    letterSpacing: typeTokens.typography['small body alt'].letterSpacing.value,
    textTransform: typeTokens.typography['small body alt'].textCase.value,
    fontFamily: typeTokens.typography['small body alt'].fontFamily.value,
    color: Colors.ColorTextLight,
  },
  caption: {
    fontSize: typeTokens.typography.caption.fontSize.value,
    lineHeight: typeTokens.typography.caption.lineHeight.value,
    fontWeight: typeTokens.typography.caption.fontWeight.value,
    letterSpacing: typeTokens.typography.caption.letterSpacing.value,
    textTransform: typeTokens.typography.caption.textCase.value,
    fontFamily: typeTokens.typography.caption.fontFamily.value,
    color: Colors.ColorTextLight,
  },
  tiny: {
    fontSize: typeTokens.typography.tiny.fontSize.value,
    lineHeight: typeTokens.typography.tiny.lineHeight.value,
    fontWeight: typeTokens.typography.tiny.fontWeight.value,
    letterSpacing: typeTokens.typography.tiny.letterSpacing.value,
    textTransform: typeTokens.typography.tiny.textCase.value,
    fontFamily: typeTokens.typography.tiny.fontFamily.value,
    color: Colors.ColorTextLight,
  },
};

export default styles;
